
@host=localhost:8080/api/v1


// Farmer API
### get all farmers 
GET http://{{host}}/user/farmer HTTP/1.1


### {farmerid}/{societyid} add farmer id to sociery id
GET http://{{host}/user/farmer/7/3 HTTP/1.1

### add farmer
POST  http://{{host}}/user/farmer HTTP/1.1
Content-Type: application/json
{
"name": "Phung Quan Phung",
"username": "quanify",
"password": "crquan07",
"email": "quanphungxuan00@gmail.com",
"address": "83 Xa Dan",
"phone": "0974654701",
"age": 21
}

//Society API

### Get all societies
GET  http://{{host}}/user/society HTTP/1.1

### Get society by id

@societyid=3
GET  http://{{host}}/user/society/{{societyid}} HTTP/1.1

### Add society

POST  http://{{host}}/user/society HTTP/1.1
Content-Type: application/json

{
"name": "Nong Nghiep Huu Van",
"username": "nong_nghiep_hv",
"password": "crquan07",
"email": "nongnghiepHV00@gmail.com",
"address": "Huu Van",
"phone": "0974654701",
"total_capital":2000.5,
"established_date":"1999-11-30",
"industry_code":"NNHV0001"
}
